name: tfsec
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tfsec:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.1.0

      - name: tfsec
        uses: tfsec/tfsec-sarif-action@master
        with:
          sarif_file: tfsec.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: tfsec.sarif

#      - name: Run Aqua Build Security
#        uses: aquasecurity/build-security-action@main
#        with:
#          aqua_cspm_url: https://stage.api.cloudsploit.com/v2/tokens
#          aqua_api_url: https://api-dev.aquasec.com/v2/iac
#          aqua_key: ${{ secrets.AQUA_KEY }}
#          aqua_secret: ${{ secrets.AQUA_SECRET }}

